[2024-12-23T06:16:07.793+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T06:16:07.830+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_pipeline.process_news scheduled__2024-12-22T22:00:00+00:00 [queued]>
[2024-12-23T06:16:07.857+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_pipeline.process_news scheduled__2024-12-22T22:00:00+00:00 [queued]>
[2024-12-23T06:16:07.860+0700] {taskinstance.py:2866} INFO - Starting attempt 3 of 2
[2024-12-23T06:16:08.002+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_news> on 2024-12-22 22:00:00+00:00
[2024-12-23T06:16:08.013+0700] {standard_task_runner.py:72} INFO - Started process 5245 to run task
[2024-12-23T06:16:08.016+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'news_pipeline', 'process_news', 'scheduled__2024-12-22T22:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmprvzr93vg']
[2024-12-23T06:16:08.020+0700] {standard_task_runner.py:105} INFO - Job 10: Subtask process_news
[2024-12-23T06:16:08.159+0700] {task_command.py:467} INFO - Running <TaskInstance: news_pipeline.process_news scheduled__2024-12-22T22:00:00+00:00 [running]> on host LAPTOP-N2PIKQNV.
[2024-12-23T06:16:08.317+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='news_pipeline' AIRFLOW_CTX_TASK_ID='process_news' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T22:00:00+00:00'
[2024-12-23T06:16:08.321+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-23T06:16:08.323+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-23T06:16:08.326+0700] {logging_mixin.py:190} INFO - Current task name:process_news state:running start_date:2024-12-22 23:16:07.833235+00:00
[2024-12-23T06:16:08.328+0700] {logging_mixin.py:190} INFO - Dag name:news_pipeline and current dag run status:running
[2024-12-23T06:16:08.331+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T06:16:08.363+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/dags/news_pipeline.py", line 36, in process_news
    df = df[["source.name", "title", "description", "url", "publishedAt"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['source.name'] not in index"
[2024-12-23T06:16:08.473+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-23T06:16:08.475+0700] {logging_mixin.py:190} INFO - Task start:2024-12-22 23:16:07.833235+00:00 end:2024-12-22 23:16:08.472402+00:00 duration:0.639167
[2024-12-23T06:16:08.477+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_news> dag:<DAG: news_pipeline> dagrun:<DagRun news_pipeline @ 2024-12-22 22:00:00+00:00: scheduled__2024-12-22T22:00:00+00:00, state:running, queued_at: 2024-12-22 23:09:15.705556+00:00. externally triggered: False>
[2024-12-23T06:16:08.480+0700] {logging_mixin.py:190} INFO - Failure caused by "['source.name'] not in index"
[2024-12-23T06:16:08.482+0700] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=news_pipeline, task_id=process_news, run_id=scheduled__2024-12-22T22:00:00+00:00, execution_date=20241222T220000, start_date=20241222T231607, end_date=20241222T231608
[2024-12-23T06:16:08.535+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T06:16:08.538+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task process_news ("['source.name'] not in index"; 5245)
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/dags/news_pipeline.py", line 36, in process_news
    df = df[["source.name", "title", "description", "url", "publishedAt"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['source.name'] not in index"
[2024-12-23T06:16:08.617+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T06:16:08.653+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T06:16:08.685+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-23T06:16:37.896+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T06:16:37.926+0700] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: news_pipeline.process_news scheduled__2024-12-22T22:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-12-23T06:16:37.930+0700] {local_task_job_runner.py:166} INFO - Task is not able to be run
