[2024-12-23T06:11:14.217+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T06:11:14.268+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_pipeline.process_news manual__2024-12-22T23:09:14.656603+00:00 [queued]>
[2024-12-23T06:11:14.294+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_pipeline.process_news manual__2024-12-22T23:09:14.656603+00:00 [queued]>
[2024-12-23T06:11:14.298+0700] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-23T06:11:14.370+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_news> on 2024-12-22 23:09:14.656603+00:00
[2024-12-23T06:11:14.381+0700] {standard_task_runner.py:72} INFO - Started process 4412 to run task
[2024-12-23T06:11:14.384+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'news_pipeline', 'process_news', 'manual__2024-12-22T23:09:14.656603+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp9oihqzbo']
[2024-12-23T06:11:14.388+0700] {standard_task_runner.py:105} INFO - Job 9: Subtask process_news
[2024-12-23T06:11:14.529+0700] {task_command.py:467} INFO - Running <TaskInstance: news_pipeline.process_news manual__2024-12-22T23:09:14.656603+00:00 [running]> on host LAPTOP-N2PIKQNV.
[2024-12-23T06:11:14.687+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='news_pipeline' AIRFLOW_CTX_TASK_ID='process_news' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T23:09:14.656603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T23:09:14.656603+00:00'
[2024-12-23T06:11:14.691+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-23T06:11:14.693+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-23T06:11:14.695+0700] {logging_mixin.py:190} INFO - Current task name:process_news state:running start_date:2024-12-22 23:11:14.270950+00:00
[2024-12-23T06:11:14.698+0700] {logging_mixin.py:190} INFO - Dag name:news_pipeline and current dag run status:running
[2024-12-23T06:11:14.700+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T06:11:14.729+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/dags/news_pipeline.py", line 36, in process_news
    df = df[["source.name", "title", "description", "url", "publishedAt"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['source.name'] not in index"
[2024-12-23T06:11:14.816+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-23T06:11:14.820+0700] {logging_mixin.py:190} INFO - Task start:2024-12-22 23:11:14.270950+00:00 end:2024-12-22 23:11:14.815893+00:00 duration:0.544943
[2024-12-23T06:11:14.823+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_news> dag:<DAG: news_pipeline> dagrun:<DagRun news_pipeline @ 2024-12-22 23:09:14.656603+00:00: manual__2024-12-22T23:09:14.656603+00:00, state:running, queued_at: 2024-12-22 23:09:14.787406+00:00. externally triggered: True>
[2024-12-23T06:11:14.825+0700] {logging_mixin.py:190} INFO - Failure caused by "['source.name'] not in index"
[2024-12-23T06:11:14.827+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=news_pipeline, task_id=process_news, run_id=manual__2024-12-22T23:09:14.656603+00:00, execution_date=20241222T230914, start_date=20241222T231114, end_date=20241222T231114
[2024-12-23T06:11:14.882+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T06:11:14.885+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task process_news ("['source.name'] not in index"; 4412)
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/dags/news_pipeline.py", line 36, in process_news
    df = df[["source.name", "title", "description", "url", "publishedAt"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['source.name'] not in index"
[2024-12-23T06:11:14.941+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T06:11:14.979+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T06:11:14.983+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
